version: '3.8'

services:
  my-apache-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-apache-php
    ports:
      - '8081:80'
    volumes:
      - ./backend:/var/www/html
    environment:
      PHP_ENABLE: "true"
      MYSQL_HOST: "mysql"
      MYSQL_DATABASE: "mydatabase"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_PORT: "3306"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: my-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
